### PR TITLE
Add pg-embedded to the list of supported projects

### PR DESCRIPTION
**Pull request by hgschmie**

### CODE REVIEW

**Comment by hgschmie** [comment]
pretty ping?

**Comment by hgschmie** [comment]
pretty ping again?

**Comment by tomix26** [comment]
No offense, but if you want to promote your project here, it might be a good idea to mention this project in your documentation first.

**Comment by hgschmie** [comment]
hey, thank you for the response!

Sorry, I thought I did. It is mentioned here:  https://pg-embedded.softwareforge.de/release-4.1/setting_postgres_version.html

Do you want me to do that more prominently? Happy to do that, let me know what you would like. I am very grateful for the prepackaged binaries and I want people to use them because it makes our lives easier.

**Comment by tomix26** [comment]
Yes, okay, you're right. But it seems to me that it's quite hidden, so I would appreciate a mention in the footer of the GitHub project, if that's not a problem. I also thought of mentioning some other related projects. So if you don't mind, I've changed your pull request a little.

**Comment by fergusstrange** [comment]
Hah, got a mention for free! Thanks guys 🙏

**Pull request merged**
