### PR TITLE
Enable optional postgis extensions

### LINKED ISSUE #4: Provide embedded postgres+postgis binaries
Would there be any interest in generating packages with the postgis extensions available?

I started investigating myself, but the current Gradle and Docker patterns doen't seem to lend themselves easily to extension. Ideally I'd expect additional artifacts to be built and extended with the `postgis` classifier, but as far as I can tell there's no clear way to reach this point without rewriting large swathes of the scripts.

I'd be happy to raise a PR for this if I could get a suggestion as to the desired approach!

### PR DESCRIPTION
**Pull request by Zetten**
Configure build and deployment of secondary artifacts with a "postgis"
classifier, by specifying "-PpostgisVersion=x.y.z" during the build.

Fixes #4

### CODE REVIEW

**Comment by Zetten** [comment]
All comments should be resolved. The typo and Dockerfile were part of my initial explorations with postgis here, sorry for leaving them in!

**Comment by tomix26** [comment]
During the testing, I made some minor changes and fixes. For example, I had to remove the postgis classifier, because otherwise Maven resolves it as a completely different dependency and it is difficult to override the original postgres dependencies. So now the applied postgis extension is part of the version of the postgis binaries, such as `10.8.0-postgis-2.5.3`.

**Comment by tomix26** [comment]
Thanks again for your contribution.

**Comment by Zetten** [comment]
Excellent! Thanks very much!

**Pull request merged**
